Dyd.BaseService.ConfigManager.Web/Controllers/CategoryController.cs
using Dyd.BaseService.ConfigManager.Domain;
using Dyd.BaseService.ConfigManager.Domain.Dal;
using Dyd.BaseService.ConfigManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Dyd.BaseService.ConfigManager.Web.Tools;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private tb_category_dal categoryrDal = new tb_category_dal();
        private tb_log_dal logDal = new tb_log_dal();


        #region 列表
        public ActionResult CategoryIndex(string name, string remark, int pageIndex = 1, int pageSize = 20)
        {
            ViewBag.Name = name;
            ViewBag.Remark = remark;
            int count = 0;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                IList<tb_category_model> list = categoryrDal.GetPageList(conn, name, remark, pageSize, pageIndex, ref count);
                PagedList<tb_category_model> pageList = new PagedList<tb_category_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_CategoryIndex", pageList);
                }
                else
                {
                    return View(pageList);
                }
            }
        }

        public JsonResult GetPagingCategoryList(int page = 1, int rows = int.MaxValue, string sort = "Id", string order = "desc")
        {
            int count = 0;

            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                string name = Request["name"];
                string remark = Request["remark"];
                conn.Open();
                IList<tb_category_model> list = categoryrDal.GetPageList(conn, name, remark, rows, page, ref count);

                var total = count;
                var items = list;
                var json = new
                {
                    total = total,
                    rows = list
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region 新增
        public ActionResult CategoryAdd()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CategoryAdd(tb_category_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    if (categoryrDal.IsExist(conn, model))
                    {
                        ModelState.AddModelError("Error", "分类名已存在！");
                        return View(model);
                    }
                    model.createtime = conn.GetServerDate();
                    var id = categoryrDal.Add(conn, model);
                    logDal.Add(conn, string.Format("{0}|{1}|{2}", "添加分类", id, model.name));
                    return RedirectToAction("CategoryIndex");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Error", exp.Message);
                    return View(model);
                }
            }
        }
        #endregion

        #region 修改
        public ActionResult CategoryEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                var model = categoryrDal.Get(conn, id);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CategoryEdit(tb_category_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    if (categoryrDal.IsExist(conn, model))
                    {
                        ModelState.AddModelError("Error", "分类名已存在！");
                        return View(model);
                    }
                    categoryrDal.Edit(conn, model);
                    logDal.Add(conn, string.Format("{0}|{1}|{2}", "编辑分类", model.id, model.name));

                    return RedirectToAction("CategoryIndex");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Error", exp.Message);
                    return View(model);
                }
            }
        }
        #endregion

        #region 删除
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CategoryDel(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    var re = categoryrDal.DelCheck(conn, id);
                    if (!re.Flag)
                    {
                        return Json(re);
                    }
                    else
                    {
                        categoryrDal.Delete(conn, id);
                        logDal.Add(conn, string.Format("{0}|{1}|{2}", "删除分类", id, ""));

                        return Json(new OperateResults { Flag = true, Message = "删除成功！" });
                    }
                }
                catch (Exception exp)
                {
                    return Json(new OperateResults { Flag = false, Message = exp.Message });
                }
            }
        }
        #endregion

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ClientReloadConfig(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    var model = categoryrDal.Get(conn, id);

                    RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                    {
                        CategoryID = model.id,
                        CommandType = XXF.BaseService.ConfigManager.SystemRuntime.EnumCommandType.ConfigReload,
                        ProjectName = ""
                    });
                    logDal.Add(conn, string.Format("{0}|{1}|{2}", "已经发送客户端重启通知", model.id, model.name));
                    return Json(new OperateResults { Flag = true, Message = "已经发送客户端重启通知！" });
                }
                catch (Exception exp)
                {
                    return Json(new OperateResults { Flag = false, Message = exp.Message });
                }
            }
        }
    }
}

Dyd.BaseService.ConfigManager.Web/Controllers/ProjectController.cs
using Dyd.BaseService.ConfigManager.Domain;
using Dyd.BaseService.ConfigManager.Domain.Dal;
using Dyd.BaseService.ConfigManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Dyd.BaseService.ConfigManager.Web.Tools;
using XXF.Extensions;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private tb_log_dal logDal = new tb_log_dal();
        private tb_project_dal projectDal = new tb_project_dal();
        private tb_category_dal categoryDal = new tb_category_dal();
        private tb_config_dal configDal = new tb_config_dal();
        #region 列表
        public ActionResult ProjectIndex(int categoryid = 0, string name = "", string remark = "", int pageIndex = 1, int pageSize = 20)
        {
            ViewBag.Name = name;
            ViewBag.Remark = remark;
            int count = 0;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();

                List<SelectListItem> ddlList = new List<SelectListItem>();
                ddlList.Add(new SelectListItem { Text = "全部", Value = " " });

                var cateList = categoryDal.GetList(conn);
                foreach (var item in cateList)
                {
                    var selected = categoryid == item.id;
                    ddlList.Add(new SelectListItem { Text = item.name, Value = item.id.ToString(), Selected = selected });
                }
                ViewBag.Category = ddlList;

                IList<tb_project_model> list = projectDal.GetPageList(conn, categoryid, name, remark, pageSize, pageIndex, ref count);

                foreach (var item in list)
                {
                    var ids = item.categoryids.Split(',').ToList();
                    //ids.Reverse();
                    foreach (var idItem in ids)
                    {
                        if (!string.IsNullOrWhiteSpace(idItem))
                        {
                            var id = Convert.ToInt32(idItem);
                            item.categorynames += cateList.FirstOrDefault(s => s.id == id).name + "->";
                        }
                    }
                    item.categorynames = item.categorynames.NullToEmpty();
                    if (item.categorynames.Length > 0)
                    {
                        item.categorynames = item.categorynames.Substring(0, item.categorynames.Length - 2);
                    }
                }

                PagedList<tb_project_model> pageList = new PagedList<tb_project_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ProjectIndex", pageList);
                }
                else
                {
                    return View(pageList);
                }
            }
        }

        #endregion

        #region 新增
        public ActionResult ProjectAdd()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                int count = 0;
                var list = categoryDal.GetPageList(conn, "", "", 100, 1, ref count);
                ViewBag.CategoryList = list;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ProjectAdd(tb_project_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    conn.BeginTransaction();
                    model.createtime = conn.GetServerDate();
                    model.lastheartbeattime = conn.GetServerDate();
                    model.projectname = model.projectname.Trim();
                    var id = projectDal.Add(conn, model);
                    RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                    {
                        CategoryID = -1,
                        CommandType = XXF.BaseService.ConfigManager.SystemRuntime.EnumCommandType.ConfigReload,
                        ProjectName = model.projectname
                    });
                    conn.Commit();
                    logDal.Add(conn, string.Format("{0}|Id:{1}|Name:{2}", "添加项目", id, model.projectname), model.projectname);
                    return Json(new OperateResults { Flag = true, Message = "添加成功！" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception exp)
                {
                    conn.Rollback();
                    return Json(new OperateResults { Flag = false, Message = exp.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion

        #region 修改
        public ActionResult ProjectEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                int count = 0;
                var list = categoryDal.GetPageList(conn, "", "", 100, 1, ref count);
                var model = projectDal.Get(conn, id);
                ViewBag.CategoryList = list;
                var ids = string.Empty;
                if (model != null && !string.IsNullOrWhiteSpace(model.categoryids))
                {
                    var start = model.categoryids.IndexOf(",");
                    var end = model.categoryids.LastIndexOf(",");
                    ids = model.categoryids.Trim(',');
                    var orderList = new List<tb_category_model>();
                    if (!string.IsNullOrWhiteSpace(ids))
                    {
                        var unOrderList = categoryDal.GetListByIds(conn, ids);
                        foreach (var item in ids.Split(','))
                        {
                            var cId = Convert.ToInt32(item);
                            orderList.Add(unOrderList.FirstOrDefault(s => s.id == cId));
                        }
                    }
                    ViewBag.ProjectCategory = orderList;
                }
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProjectEdit(tb_project_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    conn.BeginTransaction();
                    var modelsource = projectDal.Get(conn, model.id);
                    model.projectname = model.projectname.Trim();
                    model.lastheartbeattime = conn.GetServerDate();
                    projectDal.Edit(conn, model);
                    if (modelsource.projectname != model.projectname || modelsource.categoryids != model.categoryids)
                    {
                        RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                        {
                            CategoryID = -1,
                            CommandType = XXF.BaseService.ConfigManager.SystemRuntime.EnumCommandType.ConfigReload,
                            ProjectName = modelsource.projectname
                        });
                        if (modelsource.projectname != model.projectname)
                        {
                            RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                            {
                                CategoryID = -1,
                                CommandType = XXF.BaseService.ConfigManager.SystemRuntime.EnumCommandType.ConfigReload,
                                ProjectName = model.projectname
                            });
                        }
                    }
                    conn.Commit();
                    logDal.Add(conn, string.Format("{0}|Id:{1}|Name:{2}", "修改项目", model.id, model.projectname), model.projectname);
                    return Json(new OperateResults { Flag = true, Message = "修改成功！" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception exp)
                {
                    conn.Rollback();
                    return Json(new OperateResults { Flag = false, Message = exp.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion

        #region 详情
        public ActionResult ProjectDetails(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                IList<tb_config_model> allConfig = new List<tb_config_model>();

                conn.Open();
                int count = 0;
                var list = categoryDal.GetPageList(conn, "", "", 100, 1, ref count);
                var model = projectDal.Get(conn, id);
                if (model != null)
                {
                    var ids = model.categoryids.Split(',').ToList();
                    ids.Reverse();
                    foreach (var item in ids)
                    {
                        if (!string.IsNullOrWhiteSpace(item))
                        {
                            var category = categoryDal.Get(conn, Convert.ToInt32(item));
                            var configList = configDal.GetByCategoryId(conn, category.id);
                            foreach (var config in configList)
                            {
                                if (allConfig.Any(s => s.configkey == config.configkey))
                                {
                                    config.InheritanceFlag = true;
                                }

Dyd.BaseService.ConfigManager.Web/Views/Category/CategoryAdd.cshtml
@model Dyd.BaseService.ConfigManager.Domain.Model.tb_category_model

@{
    ViewBag.Title = "新增分类";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="head">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a href="javascript:void(0);" class="back fr">返回</a>
    </div>
</div>
<div>
    @using (Html.BeginForm("CategoryAdd", "Category"))
    {
        @Html.AntiForgeryToken()
        <ul class="mydetail">
            <li>
                @Html.LabelFor(model => model.name)
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </li>

            <li>
                @Html.LabelFor(model => model.remark)
                @Html.TextAreaFor(model => model.remark,15,30, new { })
                @Html.ValidationMessageFor(model => model.remark)
            </li>

            @*<li>
                @Html.LabelFor(model => model.createtime)
                @Html.EditorFor(model => model.createtime)
                @Html.ValidationMessageFor(model => model.createtime)
            </li>*@
            <li>
                <input type="submit" class="btn1" value="提交" />
                @Html.ValidationMessage("Error")
            </li>
        </ul>
    }
</div>

Dyd.BaseService.ConfigManager.Web/Views/Category/CategoryEdit.cshtml
@model Dyd.BaseService.ConfigManager.Domain.Model.tb_category_model

@{
    ViewBag.Title = "编辑分类";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="head">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a href="javascript:void(0);" class="back fr">返回</a>
    </div>
</div>
<div>
    @using (Html.BeginForm("CategoryEdit", "Category"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.createtime)
        <ul class="mydetail">
            <li>
                @Html.LabelFor(model => model.name)
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </li>

            <li>
                @Html.LabelFor(model => model.remark)
                @Html.TextAreaFor(model => model.remark,15,30, new { })
                @Html.ValidationMessageFor(model => model.remark)
            </li>
            <li>
                <input type="submit" class="btn1" value="提交" />
                @Html.ValidationMessage("Error")
            </li>
        </ul>
    }
</div>

Dyd.BaseService.ConfigManager.Web/Views/Category/CategoryIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_category_model>
@{
    ViewBag.Title = "分类列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.AntiForgeryToken()
<div class="head">
    <div class="title">
        @ViewBag.Title
    </div>
</div>
<div>
    @Html.ActionLink("新增", "CategoryAdd", null, new { @class = "btn1",target="_blank" })
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("CategoryIndex", "Category", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="search">

            <label>分类名</label><input type="text" class="text midtext" style="width:150px;" name="name" value="@ViewBag.Name" />

            <label>备注</label><input type="text" class="text midtext" style="width:200px;" name="remark" value="@ViewBag.Remark" />

            <input type="submit" class="btn1" value="搜索" accesskey="S" />
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("_CategoryIndex", Model)
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(function () {
            $("body").on("click", ".edit", function () {
                var id = $(this).parent().parent().attr("data-id");
                var url = "/Category/CategoryEdit/" + id;
                window.location = url;
            });

            $("body").on("click", ".del", function (e) {
                var id = $(this).parent().parent().attr("data-id");
                var url = "/Category/CategoryDel";
                if (window.confirm("确定要删除吗？")) {
                    $.post(url, addAntiForgeryToken({ id: id }), function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        }
                        else {
                            alert(data.Message);
                        }
                    }, "json");
                }
            });

            $("body").on("click", ".reload", function (e) {
                var id = $(this).parent().parent().attr("data-id");
                var url = "/Category/ClientReloadConfig";
                if (window.confirm("确定要通知客户端重新初始化项目配置吗？")) {
                    $.post(url, addAntiForgeryToken({ id: id }), function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        }
                        else {
                            alert(data.Message);
                        }
                    }, "json");
                }
            });
        });

    </script>
}

Dyd.BaseService.ConfigManager.Web/Views/Category/_CategoryIndex.cshtml
@using Webdiyer.WebControls.Mvc
@using XXF.Extensions;
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_category_model>

<table class="mytable" width="100%">
    <tr>
        <th style="width:5%">Id</th>
        <th style="width:15%">名称</th>
        <th style="width:50%">备注</th>
        <th style="width:15%">创建时间</th>
        <th style="width:15%">操作</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr data-id="@item.id">
            <td>@item.id</td>
            <td style="text-align:left;">@item.name</td>
            <td style="text-align:left" title="@item.remark">@item.remark.SubString3(55)</td>
            <td>@item.createtime</td>
            <td>
                <a href="#" class="edit">修改</a>
                <a href="#" class="del">删除</a>
                 <a href="#" class="reload" title="通知客户端重新加载配置">客户端重启</a>
                <a href="@Url.Action("ProjectIndex", "Project", new {categoryid=item.id })" target="_blank">相关项目</a>
            </td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
</div>