Dyd.BaseService.ConfigManager.Web/Controllers/ConfigController.cs
using Dyd.BaseService.ConfigManager.Domain;
using Dyd.BaseService.ConfigManager.Domain.Dal;
using Dyd.BaseService.ConfigManager.Domain.Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using System.Linq;
using XXF.Extensions;
using Dyd.BaseService.ConfigManager.Web.Tools;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    [Authorize]
    public class ConfigController : Controller
    {
        private tb_log_dal logDal = new tb_log_dal();
        tb_failover_dal failOverDal = new tb_failover_dal();
        tb_loadbalance_dal loadBalanceDal = new tb_loadbalance_dal();
        private tb_config_dal configDal = new tb_config_dal();
        private tb_category_dal categoryDal = new tb_category_dal();
        #region 列表
        public ActionResult ConfigIndex(DateTime? startTime, DateTime? endTime, int categoryid = 0, string configkey = "", string configvalue = "", string remark = "", int pageIndex = 1, int pageSize = 20)
        {
            if (startTime != null)
            {
                startTime = startTime.Value;
            }
            else
            {
                startTime = DateTime.Now.AddDays(-30);
            }
            if (endTime != null)
            {
                endTime = endTime.Value;
            }
            else
            {
                endTime = DateTime.Now.AddDays(1);
            }
            ViewBag.startTime = startTime;
            ViewBag.endTime = endTime;
            ViewBag.CategoryId = categoryid;
            ViewBag.Configkey = configkey;
            ViewBag.Configvalue = configvalue; ViewBag.remark = remark;
            int count = 0;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                List<SelectListItem> ddlList = new List<SelectListItem>();
                ddlList.Add(new SelectListItem { Text = "全部", Value = "0" });

                var categoryList = categoryDal.GetList(conn);
                foreach (var item in categoryList)
                {
                    var selected = categoryid == item.id;
                    ddlList.Add(new SelectListItem { Text = item.name, Value = item.id.ToString(), Selected = selected });
                }
                ViewBag.Category = ddlList;

                IList<tb_config_model> list = configDal.GetPageList(conn, startTime, endTime, categoryid, configkey, configvalue, remark, pageSize, pageIndex, ref count);
                PagedList<tb_config_model> pageList = new PagedList<tb_config_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ConfigIndex", pageList);
                }
                else
                {
                    return View(pageList);
                }
            }
        }
        #endregion

        #region 新增
        public ActionResult ConfigAdd()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                List<SelectListItem> list = new List<SelectListItem>();

                var categoryList = categoryDal.GetList(conn);
                foreach (var item in categoryList)
                {
                    list.Add(new SelectListItem { Text = item.name, Value = item.id.ToString() });
                }
                ViewBag.Category = list;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ConfigAdd(tb_config_model model, string loadBalance, string failLoad, string loadBalanceSwitch, string failOverSwitch)
        {
            List<tb_failover_model> failoverList = JsonConvert.DeserializeObject<List<tb_failover_model>>(failLoad);
            List<tb_loadbalance_model> loadBalanceList = JsonConvert.DeserializeObject<List<tb_loadbalance_model>>(loadBalance);

            model.configkey = model.configkey ?? "";
            model.configvalue = model.configvalue.NullToEmpty();

            for (int i = 0, length = failoverList.Count; i < length; i++)
            {
                failoverList[i].sequence = Convert.ToInt16(i + 1);
            }

            for (int i = 0, length = loadBalanceList.Count; i < length; i++)
            {
                loadBalanceList[i].sequence = Convert.ToInt16(i + 1);
            }

            if (!string.IsNullOrEmpty(failOverSwitch))
            {
                if (failoverList.Count > 0)
                {
                    model.failoversequence = failoverList.OrderByDescending(s => s.id).FirstOrDefault().id;
                }
            }
            else
            {
                model.failoversequence = -1;
            }

            if (!string.IsNullOrEmpty(loadBalanceSwitch))
            {
                model.loadbalancealgorithmenum = 1;
            }
            else
            {
                model.loadbalancealgorithmenum = -1;
            }

            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();

                    if (configDal.IsExist(conn, model))
                    {
                        return Json(new OperateResults { Flag = false, Message = "当前分类下配置Key重复！" }, JsonRequestBehavior.AllowGet);
                    }
                    conn.BeginTransaction();
                    model.createtime = conn.GetServerDate();
                    model.lastupdatetime = conn.GetServerDate();
                    var id = configDal.Add(conn, model, failoverList, loadBalanceList);
                    RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                    {
                        CategoryID = model.categoryid,
                        CommandType = XXF.BaseService.ConfigManager.SystemRuntime.EnumCommandType.ConfigUpdate,
                        ProjectName = ""
                    });
                    conn.Commit();

                    logDal.Add(conn, string.Format("{0}|id:{1}|key:{2}|value:{3}", "添加配置", id, model.configkey, model.configvalue), "", model.categoryid);
                    return Json(new OperateResults { Flag = true, Message = "添加成功！" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception exp)
                {
                    conn.Rollback();
                    return Json(new OperateResults { Flag = false, Message = exp.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion

        #region 修改
        public ActionResult ConfigEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                List<SelectListItem> list = new List<SelectListItem>();

                var categoryList = categoryDal.GetList(conn);
                foreach (var item in categoryList)
                {
                    list.Add(new SelectListItem { Text = item.name, Value = item.id.ToString() });
                }
                ViewBag.Category = list;

                var model = configDal.Get(conn, id);
                ViewBag.LoadBalanceList = loadBalanceDal.GetListByConfigId(conn, id);
                ViewBag.FailOverList = failOverDal.GetListByConfigId(conn, id);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public JsonResult ConfigEdit(tb_config_model model, string loadBalance, string failLoad, string loadBalanceSwitch, string failOverSwitch)
        {
            List<tb_failover_model> failoverList = JsonConvert.DeserializeObject<List<tb_failover_model>>(failLoad);
            List<tb_loadbalance_model> loadBalanceList = JsonConvert.DeserializeObject<List<tb_loadbalance_model>>(loadBalance);
            model.configkey = model.configkey ?? "";
            model.configvalue = model.configvalue.NullToEmpty();
            for (int i = 0, length = failoverList.Count; i < length; i++)
            {
                failoverList[i].sequence = Convert.ToInt16(i + 1);
            }

            for (int i = 0, length = loadBalanceList.Count; i < length; i++)
            {
                loadBalanceList[i].sequence = Convert.ToInt16(i + 1);
            }

            if (!string.IsNullOrEmpty(failOverSwitch))
            {
                if (failoverList.Count > 0)
                {
                    model.failoversequence = failoverList.OrderByDescending(s => s.id).FirstOrDefault().id;
                }
            }
            else
            {
                model.failoversequence = -1;
            }

            if (!string.IsNullOrEmpty(loadBalanceSwitch))
            {
                model.loadbalancealgorithmenum = 1;
            }
            else
            {
                model.loadbalancealgorithmenum = -1;
            }
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    if (configDal.IsExist(conn, model))
                    {
                        return Json(new OperateResults { Flag = false, Message = "当前分类下配置Key重复！" }, JsonRequestBehavior.AllowGet);
                    }
                    conn.BeginTransaction();
                    model.createtime = conn.GetServerDate();
                    model.lastupdatetime = conn.GetServerDate();
                    configDal.Edit(conn, model, failoverList, loadBalanceList);
                    RedisHelper.SendCommand(new XXF.BaseService.ConfigManager.SystemRuntime.ConfigNetCommand()
                    {

Dyd.BaseService.ConfigManager.Web/Controllers/SystemConfigController.cs
using Dyd.BaseService.ConfigManager.Domain;
using Dyd.BaseService.ConfigManager.Domain.Dal;
using Dyd.BaseService.ConfigManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using XXF.Db;
using Dyd.BaseService.ConfigManager.Web.Tools;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    [Authorize]
    public class SystemConfigController : Controller
    {
        private tb_log_dal logDal = new tb_log_dal();
        private tb_systemconfig_dal systemconfigDal = new tb_systemconfig_dal();

        #region 列表
        public ActionResult SystemConfigIndex(string key, string value, string remark, int pageIndex = 1, int pageSize = 20)
        {
            int count = 0;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                ViewBag.Key = key;
                ViewBag.Value = value;
                ViewBag.Remark = remark;
                conn.Open();
                IList<tb_systemconfig_model> list = systemconfigDal.GetPageList(conn, key, value, remark, pageIndex, pageSize, ref count);
                PagedList<tb_systemconfig_model> pageList = new PagedList<tb_systemconfig_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_SystemConfigIndex", pageList);
                }
                else
                {
                    return View(pageList);
                }
            }
        }
        #endregion

        #region 新增
        public ActionResult SystemConfigAdd()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SystemConfigAdd(tb_systemconfig_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                try
                {
                    if (systemconfigDal.IsExist(conn, model))
                    {
                        return Json(new OperateResults { Flag = false, Message = "Key重复！" }, JsonRequestBehavior.AllowGet);
                    }
                    var id = systemconfigDal.Add(conn, model);
                    logDal.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "添加系统配置", id, model.key, model.value));
                    RedisHelper.LoadRedisServer();
                    return Json(new OperateResults { Flag = true, Message = "添加成功！" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception exp)
                {
                    return Json(new OperateResults { Flag = false, Message = exp.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        #endregion

        #region 修改
        public ActionResult SystemConfigEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                var model = systemconfigDal.Get(conn, id);
                return View(model);
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SystemConfigEdit(tb_systemconfig_model model)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                try
                {
                    if (systemconfigDal.IsExist(conn, model))
                    {
                        return Json(new OperateResults { Flag = false, Message = "Key重复！" }, JsonRequestBehavior.AllowGet);
                    }
                    systemconfigDal.Edit(conn, model);
                    logDal.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "修改系统配置", model.id, model.key, model.value));
                    RedisHelper.LoadRedisServer();
                    return Json(new OperateResults { Flag = true, Message = "修改成功！" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception exp)
                {
                    return Json(new OperateResults { Flag = false, Message = exp.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion

        #region 删除
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult SystemConfigDel(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                try
                {
                    conn.Open();
                    var model = systemconfigDal.Get(conn, id);
                    systemconfigDal.Delete(conn, id);
                    logDal.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "删除系统配置", model.id, model.key, model.value));
                    return Json(new OperateResults { Flag = true, Message = "删除成功！" });
                }
                catch (Exception exp)
                {
                    return Json(new OperateResults { Flag = false, Message = exp.Message });
                }
            }
        }
        #endregion
    }
}

Dyd.BaseService.ConfigManager.Web/Views/SystemConfig/SystemConfigAdd.cshtml
@model Dyd.BaseService.ConfigManager.Domain.Model.tb_systemconfig_model

@{
    ViewBag.Title = "新增系统配置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="head">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a href="javascript:void(0);" class="back fr">返回</a>
    </div>
</div>
<div>
    @using (Html.BeginForm("SystemConfigAdd", "Config"))
    {
        @Html.AntiForgeryToken()
        <ul class="mydetail">
            <li>
                @Html.LabelFor(model => model.key)
                @Html.EditorFor(model => model.key)
                @Html.ValidationMessageFor(model => model.key)
            </li>

            <li>
                @Html.LabelFor(model => model.value)
                @Html.EditorFor(model => model.value)
                @Html.ValidationMessageFor(model => model.value)
            </li>
            <li>
                @Html.LabelFor(model => model.remark)
                @Html.TextAreaFor(model => model.remark)
                @Html.ValidationMessageFor(model => model.remark)
            </li>
            <li>
                <input id="save" type="button" class="btn1" value="提交" />
                @Html.ValidationMessage("Error")
            </li>
        </ul>
    }
</div>
@section Scripts{
    <script>
        $(function () {

            $("#save").click(function () {
                var submitJson = $("form").serialize();
                $.ajax({
                    url: "/SystemConfig/SystemConfigAdd",
                    data: addAntiForgeryToken(submitJson),
                    type: "post",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.href = "/SystemConfig/SystemConfigIndex";
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            });
        });

    </script>

}

Dyd.BaseService.ConfigManager.Web/Views/SystemConfig/SystemConfigEdit.cshtml
@model Dyd.BaseService.ConfigManager.Domain.Model.tb_systemconfig_model

@{
    ViewBag.Title = "编辑系统配置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="head">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a href="javascript:void(0);" class="back fr">返回</a>
    </div>
</div>
<div>
    @using (Html.BeginForm("SystemConfigEdit", "Config"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)
        <ul class="mydetail">
            <li>
                @Html.LabelFor(model => model.key)
                @Html.EditorFor(model => model.key)
                @Html.ValidationMessageFor(model => model.key)
            </li>
            <li>
                @Html.LabelFor(model => model.value)
                @Html.EditorFor(model => model.value)
                @Html.ValidationMessageFor(model => model.value)
            </li>
            <li>
                @Html.LabelFor(model => model.remark)
                @Html.TextAreaFor(model => model.remark)
                @Html.ValidationMessageFor(model => model.remark)
            </li>
            <li>
                <input id="save" type="button" class="btn1" value="提交" />
                @Html.ValidationMessage("Error")
            </li>
        </ul>
    }
</div>
@section Scripts{
    <script>
        $(function () {

            $("#save").click(function () {
                var submitJson = $("form").serialize();
                $.ajax({
                    url: "/SystemConfig/SystemConfigEdit",
                    data: addAntiForgeryToken(submitJson),
                    type: "post",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.href = "/SystemConfig/SystemConfigIndex";
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            });
        });

    </script>
}

Dyd.BaseService.ConfigManager.Web/Views/SystemConfig/SystemConfigIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_systemconfig_model>
@{
    ViewBag.Title = "系统配置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="head">
    <div class="title">
        @ViewBag.Title
    </div>
</div>
<div>
    @Html.ActionLink("新增", "SystemConfigAdd", null, new { @class = "btn1" })
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("SystemConfigIndex", "SystemConfig", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="search">
            <label>键</label><input type="text" class="text midtext" style="width:120px;" name="key" value="@ViewBag.Key" />

            <label>值</label><input type="text" class="text midtext" style="width:200px;" name="value" value="@ViewBag.Value" />

            <label>备注</label><input type="text" class="text midtext" style="width:200px;" name="remark" value="@ViewBag.Remark" />

            <input type="submit" class="btn1" value="搜索" accesskey="S" />
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("_SystemConfigIndex", Model)
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(function () {
            $("body").on("click", ".edit", function () {
                var id = $(this).parent().parent().attr("data-id");
                var url = "/SystemConfig/SystemConfigEdit/" + id;
                window.location = url;
            });

            $("body").on("click", ".del", function (e) {
                var id = $(this).parent().parent().attr("data-id"); 
                var url = "/SystemConfig/SystemConfigDel/";
                if (window.confirm("确定要删除吗？")) {
                    $.post(url, { id: id }, function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        }
                        else {
                            alert(data.Message);
                        }
                    }, "json");
                }
            });
        });
    </script>
}

Dyd.BaseService.ConfigManager.Web/Views/SystemConfig/_SystemConfigIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_systemconfig_model>

<table class="mytable" width="100%">
    <tr>
        <th style="width:15%;">键</th>
        <th style="width:15%;">值</th>
        <th style="width:55%">备注</th>
        <th style="width:15%">操作</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr data-id="@item.id">
            <td>@item.key</td>
            <td>@item.value</td>
            <td>@item.remark</td>
            <td><a class="edit" style="cursor:pointer">修改</a> <a class="del" style="cursor:pointer">删除</a></td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
</div>