Dyd.BaseService.ConfigManager.Web/Controllers/LogController.cs
using Dyd.BaseService.ConfigManager.Domain;
using Dyd.BaseService.ConfigManager.Domain.Dal;
using Dyd.BaseService.ConfigManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using XXF.Db;

namespace Dyd.BaseService.ConfigManager.Web.Controllers
{
    [Authorize]
    public class LogController : Controller
    {
        private tb_log_dal logDal = new tb_log_dal();
        #region 列表
        public ActionResult LogIndex(DateTime? startTime, DateTime? endTime, string projectname, string info, int pageIndex = 1, int pageSize = 20)
        {

            if (startTime != null)
            {
                startTime = startTime.Value;
            }
            else
            {
                startTime = DateTime.Now.AddDays(-30);
            }
            if (endTime != null)
            {
                endTime = endTime.Value;
            }
            else
            {
                endTime = DateTime.Now.AddDays(1);
            }

            ViewBag.startTime = startTime;
            ViewBag.endTime = endTime;
            ViewBag.projectname = projectname;
            ViewBag.info = info;

            int count = 0;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                IList<tb_log_model> list = logDal.GetPageList(conn, startTime, endTime, projectname, info, pageSize, pageIndex, ref count);
                PagedList<tb_log_model> pageList = new PagedList<tb_log_model>(list, pageIndex, pageSize, count);
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_LogIndex", pageList);
                }
                else
                {
                    return View(pageList);
                }
            }
        }
        #endregion

        #region 清理日志
        [HttpPost]
        public JsonResult LogClear()
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ConfigMangeConnectString))
            {
                conn.Open();
                logDal.Clear(conn);
                logDal.Add(conn, string.Format("{0}", "清理日志"));
                return Json(new OperateResults { Flag = true, Message = "清理成功！" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

Dyd.BaseService.ConfigManager.Web/Views/Log/LogIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_log_model>
@{
    ViewBag.Title = "常用日志";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.AntiForgeryToken()
<div class="head">
    <div class="title">
        @ViewBag.Title
    </div>
</div>
<div class="orderlist m10 myorder">
    @using (Html.BeginForm("LogIndex", "Log", FormMethod.Get, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="search">

            <label>时间</label><input type="text" class="text midtext" style="width:150px;" onclick="WdatePicker()" name=" starttime" value="@ViewBag.startTime.ToString("yyyy-MM-dd")" />
            -<input type="text" class="text midtext" style="width:150px;" name="endTime" onclick="WdatePicker()" value="@ViewBag.endTime.ToString("yyyy-MM-dd")" />

            <label>项目</label><input type="text" class="text midtext" style="width:150px;" name="projectname" value="@ViewBag.projectname" />

            <label>详细信息</label><input type="text" class="text midtext" style="width:200px;" name="info" value="@ViewBag.info" />

            <input type="submit" class="btn1" value="搜索" accesskey="S" />
            <input id="clear" type="button" class="btn1" value="清空" />
        </div>
    }
    <div class="tab_cont">
        <div class="List">
            @Html.Partial("_LogIndex", Model)
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(function () {
            $("body").on("click", "#clear", function (e) {
                var id = $(this).parent().parent().attr("data-id");
                var url = "/Log/LogClear";
                if (window.confirm("确定要删除吗？")) {
                    $.post(url, addAntiForgeryToken({ id: "" }), function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        }
                        else {
                            alert(data.Message);
                        }
                    }, "json");
                }
            });
        });

    </script>
}

Dyd.BaseService.ConfigManager.Web/Views/Log/_LogIndex.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<Dyd.BaseService.ConfigManager.Domain.Model.tb_log_model>

<table class="mytable" width="100%">
    <tr>
        <th style="width:15%;">项目名称</th>
        <th style="width:10%">分类id</th>
        <th style="width:60%">日志详情</th>
        <th style="width:15%;">创建时间</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.projectname</td>
            <td style="text-align:left;">@item.categoryname</td>
            <td style="text-align:left" title="【@item.info">@item.info</td>
            <td>@item.createtime</td>
        </tr>
    }
</table>
<div class="total pt10">
    <div class="fl">共<em>@Model.TotalPageCount</em>页<em>@Model.TotalItemCount</em>条记录，当前为第<em>@Model.CurrentPageIndex</em>页</div>
    @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex", ShowPageIndexBox = true, PageIndexBoxType = PageIndexBoxType.TextBox, CssClass = "mvcPager" })
</div>